site_name: Documentation utilisateur ISTEX
pages:
- Accueil: index.md
- INTEGRATION D'ISTEX:
  - Configurer votre Discovery Tool: integration/discovery.md
  - Configurer votre Logiciel de Gestion Bibliographique: integration/logiciel.md
  - Configurer votre navigateur: integration/navigateur.md
- FAQ:
  - A quoi sert ISTEX ?: faq/aquoisertISTEX.md
  - Mais pourquoi mettre un ARK ?: faq/ark.md 
theme: readthedocs
docs_dir: docs
site_dir: public/documentation
extra_javascript:
  - //content-delivery.istex.fr/web-header/main.js
extra_css:
  - css/docs.css
