site_name: Documentation utilisateur ISTEX
pages:
- Accueil: index.md
- Configurer votre Discovery Tool: discovery.md
- Configurer votre Logiciel de Gestion Bibliographique: logiciel.md
- Configurer votre navigateur: navigateur.md
- FAQ: faq.md
theme: readthedocs
docs_dir: docs
site_dir: public/documentation
extra_javascript:
  - //content-delivery.istex.fr/web-header/main.js
extra_css:
  - css/docs.css
